// remix/app/routes/name.tsx
import { type ActionFunctionArgs, redirect } from "@remix-run/node";
import { Form } from "@remix-run/react";

export async function action({ request }: ActionFunctionArgs) {
  // Process form data and perform necessary actions
  return redirect("/summary");
}

export default function Name() {
  return (
    <div className="govuk-grid-row">
      <div className="govuk-grid-column-two-thirds">
        <Form method="post">
          <div className="govuk-form-group">
            <h1 className="govuk-label-wrapper">
              <label
                className="govuk-label govuk-label--l"
                htmlFor="enter-email"
              >
                Enter your name
              </label>
            </h1>

            <input
              className="govuk-input"
              id="enter-email"
              name="name"
              type="text"
            />
          </div>

          <button
            type="submit"
            className="govuk-button"
            data-module="govuk-button"
          >
            Continue
          </button>
        </Form>
      </div>
    </div>
  );
}

// sveltekit/src/routes/name/+page.svelte
<script>
	import { enhance } from '$app/forms';
</script>

<div class="govuk-grid-row">
	<div class="govuk-grid-column-two-thirds">
		<form method="post" id="nameForm" action="/name" use:enhance>
			<div class="govuk-form-group">
				<h1 class="govuk-label-wrapper">
					<label class="govuk-label govuk-label--l" for="enter-email"> Enter your name </label>
				</h1>

				<input class="govuk-input" id="enter-email" name="name" type="text" />
			</div>

			<button type="submit" class="govuk-button" data-module="govuk-button"> Continue </button>
		</form>
	</div>
</div>
